Class Producto creado
chmalo/onboarding-php-testing pull request #5
Opened 2024-10-10 22:29 UTC by Programador-Luis

2024-10-10 22:32 UTC, chmalo requested changes
@Programador-Luis

2024-10-10 22:32 UTC, chmalo commented on src/Luis/Product.php
> +    public function applyDiscount($percentage)
@Programador-Luis tipeado de salida de este metodo

2024-10-10 22:32 UTC, chmalo commented on src/Luis/Product.php
> +$producto = new Product("arroz", 100);
elimina estas lineas, trabaja usando los test para ver la informacion

2024-10-11 18:00 UTC, Programador-Luis commented on src/Luis/Product.php
> +    public function applyDiscount($percentage)
@chmalo Realizado

2024-10-11 18:01 UTC, Programador-Luis commented on src/Luis/Product.php
> +$producto = new Product("arroz", 100);
@chmalo Realizado

2024-10-15 14:08 UTC, chmalo commented on src/Luis/ProductClothes.php
> +    public function applyDiscount($percentage): void
Esto lo podemos mejorar @Programador-Luis

2024-10-15 14:09 UTC, chmalo commented on tests/Luis/ProductTest.php
> +
Cada test debe ser aplicado por cada clase, ejemplo: si tenemos la clase ElectronicProduct se debe tener el test ElectronicProductTest @Programador-Luis

2024-10-15 14:10 UTC, chmalo requested changes
@Programador-Luis

2024-10-15 15:13 UTC, Programador-Luis commented on src/Luis/Product.php
> +    private function valitePrice(float $precio): float
Realizado pana @chmalo 

Se me había olvidado colocarlo en el constructor!

2024-10-15 23:21 UTC, Programador-Luis commented on src/Luis/ProductClothes.php
> +    public function applyDiscount($percentage): void
@chmalo Si lo podemos hacer en llamada mañana, estaría bueno.

2024-10-15 23:21 UTC, Programador-Luis commented on tests/Luis/ProductTest.php
> +
Realizado esta parte mi pana @chmalo

2024-10-16 15:43 UTC, chmalo commented on src/Luis/ClothesProduct.php
> +
es necesario aplicar constructores para cada clase @Programador-Luis

2024-10-16 15:43 UTC, chmalo commented on src/Luis/ElectronicProduct.php
> +
es necesario aplicar constructores para cada clase @Programador-Luis

2024-10-16 15:46 UTC, chmalo requested changes
@Programador-Luis

2024-10-16 19:59 UTC, Programador-Luis commented on src/Luis/ClothesProduct.php
> +
Realizado

2024-10-16 19:59 UTC, Programador-Luis commented on src/Luis/ElectronicProduct.php
> +
Realizado!

2024-10-16 20:00 UTC, Programador-Luis commented on src/Luis/Product.php
> +        $this->price = $price;
Realizado!

2024-10-18 22:04 UTC, chmalo approved these changes
👍 @Programador-Luis

2024-10-18 22:04 UTC, merged