Version con Test Yeiquel 6.0
chmalo/onboarding-php-testing pull request #9
Opened 2024-10-21 03:41 UTC by DavoCardier

2024-10-21 14:55 UTC, chmalo commented on src/Yeiquel/FoodProduct.php
> +class FoodProduct extends Product {
acomoda la identacion @DavoCardier

2024-10-21 14:57 UTC, chmalo commented on src/Yeiquel/FoodProduct.php
> +    public function __construct(string $name, float $price, string $expirationDate) {
tienes que mejorar esto, puedes guiarte del que hiciste anteriormente y ver que cosas puedes mejorar pero no deberias aplicar los metodos en el constructor

2024-10-21 14:59 UTC, chmalo commented on src/Yeiquel/FoodProduct.php
> +    public function applyDiscount(): void {
la aplicacion del descuento la puedes mejorar, trata de guiarte de lo que hiciste antes pero recuerda que una de las primeras cosas que debe hacer la clase es tener un descuento del 10% por defauld, sin importar si le estas aplicando descuento o no

2024-10-21 15:01 UTC, chmalo commented on src/Yeiquel/FoodProduct.php
> +        $date = \DateTime::createFromFormat('Y-m-d', $validDate);
aqui puedes mejorar esto aplicando una clausula de guarda por $validDate no viene en formato fecha y en caso que si haga el proceso de comparacion

2024-10-21 15:03 UTC, chmalo commented on tests/Yeiquel/FoodProductTest.php
> +    public function testApplyDiscountAutomatically()
hay que mejorar los test, con la aplicacion de los descuentos correspondientes

2024-10-21 15:04 UTC, chmalo requested changes
@DavoCardier

2024-10-24 02:57 UTC, DavoCardier commented
Cambios de solicitados.

2024-10-25 12:30 UTC, chmalo approved these changes
👍 @DavoCardier

2024-10-25 12:31 UTC, merged